AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

require:
  - rubocop-rake
  - rubocop-rspec

